version: "3"

services:
  ball8:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/ball
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - "mongodata:/data/db"
volumes:
  mongodata:
